/* NOTE: require() only works with static file paths, that's why the code below looks like that */
export default {
    reqFiles: [   
        require('../../imgs/mapIcons/clusters/0.png'),
        require('../../imgs/mapIcons/clusters/5.png'),
        require('../../imgs/mapIcons/clusters/10.png'),
        require('../../imgs/mapIcons/clusters/15.png'),
        require('../../imgs/mapIcons/clusters/20.png'),
        require('../../imgs/mapIcons/clusters/25.png'),
        require('../../imgs/mapIcons/clusters/30.png'),
        require('../../imgs/mapIcons/clusters/35.png'),
        require('../../imgs/mapIcons/clusters/40.png'),
        require('../../imgs/mapIcons/clusters/45.png'),
        require('../../imgs/mapIcons/clusters/50.png'),
        require('../../imgs/mapIcons/clusters/55.png'),
        require('../../imgs/mapIcons/clusters/60.png'),
        require('../../imgs/mapIcons/clusters/65.png'),
        require('../../imgs/mapIcons/clusters/70.png'),
        require('../../imgs/mapIcons/clusters/75.png'),
        require('../../imgs/mapIcons/clusters/79.png'),
        require('../../imgs/mapIcons/clusters/83.png'),
        require('../../imgs/mapIcons/clusters/86.png'),
        require('../../imgs/mapIcons/clusters/88.png'),
        require('../../imgs/mapIcons/clusters/90.png'),
        require('../../imgs/mapIcons/clusters/91.png'),
        require('../../imgs/mapIcons/clusters/92.png'),
        require('../../imgs/mapIcons/clusters/93.png'),
        require('../../imgs/mapIcons/clusters/94.png'),
        require('../../imgs/mapIcons/clusters/95.png'),
        require('../../imgs/mapIcons/clusters/96.png'),
        require('../../imgs/mapIcons/clusters/97.png'),
        require('../../imgs/mapIcons/clusters/98.png'),
        require('../../imgs/mapIcons/clusters/99.png'),
        require('../../imgs/mapIcons/clusters/100.png')
    ],
    imgLevels: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 79, 83, 86, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
}