require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'guardioesapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  #NEW PODS
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'
  
  pod 'OneSignal', '>= 2.9.3', '< 3.0'

  target 'guardioesappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
